FROM python:3.10-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

COPY requirements.txt .
# Lệnh này sẽ cài psutil và các thư viện khác
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "war.py"]
